---
appveyor.yml:
  delete: true
.yardopts:
  delete: true
.gitlab-ci.yml:
  delete: true
.gitignore:
  required:
    - 'appveyor.yml'
    - '.gitlab-ci.yml'
    - '*.sublime-*'
Rakefile:
  default_disabled_lint_checks:
    - '140chars'
    - 'arrow_alignment'
spec/spec_helper.rb:
  hiera_config: 'spec/fixtures/hiera.yaml'
  mock_with: ':rspec'
Gemfile:
  optional:
    ':development':
      - gem: 'github_changelog_generator'
